---

- hosts: Agents
  remote_user: root
  vars_files:
    - vars/main.yml
  vars:
    - id: 1
    - job_options: reload
    - date_interval: date now

  tasks:
    - name: Enable Transmission
      copy: src={{ filter_path }} dest={{ application_path }}
     
    - include: ../../../roles/agents/tasks/start_job.yml

