# 
#   OpenBACH is a generic testbed able to control/configure multiple
#   network/physical entities (under test) and collect data from them. It is
#   composed of an Auditorium (HMIs), a Controller, a Collector and multiple
#   Agents (one for each network entity that wants to be tested).
#   
#   
#   Copyright Â© 2016 CNES
#   
#   
#   This file is part of the OpenBACH testbed.
#   
#   
#   OpenBACH is a free software : you can redistribute it and/or modify it under the
#   terms of the GNU General Public License as published by the Free Software
#   Foundation, either version 3 of the License, or (at your option) any later
#   version.
#   
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS
#   FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
#   details.
#   
#   You should have received a copy of the GNU General Public License along with
#   this program. If not, see http://www.gnu.org/licenses/.
#   
#   
#   
#   @file     install_frontend_scripts.yml
#   @brief    Tasks that install the frontend scripts
#   @author   Adrien THIBAUD <adrien.thibaud@toulouse.viveris.com>


---

- name: Create Auditorium repository
  file: path=/opt/openbach-auditorium/frontend_scripts/ state=directory

- name: Install frontend scripts
  copy: src=../src/auditorium/frontend_scripts/{{ item }} dest=/opt/openbach-auditorium/frontend_scripts/ mode=0755
  with_items:
    - add_job.py
    - create_scenario.py
    - del_job.py
    - del_scenario.py
    - get_job_help.py
    - get_job_stats.py
    - get_scenario.py
    - install_agent.py
    - install_jobs.py
    - kill_all.py
    - list_agents.py
    - list_installed_jobs.py
    - list_job_instances.py
    - list_jobs.py
    - list_scenario_instances.py
    - list_scenarios.py
    - modify_scenario.py
    - push_file.py
    - restart_job_instance.py
    - set_job_log_severity.py
    - set_job_stat_policy.py
    - start_job_instance.py
    - start_scenario_instance.py
    - status_agents.py
    - status_job_instance.py
    - status_jobs.py
    - status_scenario_instance.py
    - stop_job_instance.py
    - stop_scenario_instance.py
    - uninstall_agent.py
    - uninstall_jobs.py
    - watch_job_instance.py
    - status_install_agent.py
    - status_uninstall_agent.py
    - status_retrieve_status_agents.py
    - status_install_jobs.py
    - status_uninstall_jobs.py
    - status_retrieve_status_jobs.py
    - status_set_job_log_severity.py
    - status_set_job_stat_policy.py
    - status_push_file.py
    - status_start_job_instance.py
    - status_stop_job_instance.py
    - status_restart_job_instance.py
    - status_watch_job_instance.py

- name: Install frontend scripts (2)
  template: src=../src/auditorium/frontend_scripts/frontend.py.j2 dest=/opt/openbach-auditorium/frontend_scripts/frontend.py

