---

# Install
- include: install_stats.yml
  tags:
    - install
- include: install_logs.yml
  tags:
    - install
- include: install_frontend_scripts.yml
  tags:
    - install
- include: add_jobs.yml
  tags:
    - install
- include: add_services_to_boot.yml
  tags:
    - install
- include: install_agent.yml
  tags:
    - install

# Uninstall
- include: uninstall_stats.yml
  tags:
    - uninstall
- include: uninstall_logs.yml
  tags:
    - uninstall
- include: uninstall_frontend_scripts.yml
  tags:
    - uninstall
- include: del_services_to_boot.yml
  tags:
    - uninstall

