---

- name: Create /opt directory
  file: path=/opt state=directory

- name: Download and Uncompress Kibana
  unarchive: src=https://download.elastic.co/kibana/kibana/kibana-{{ version_kibana }}-linux-{{ controller_archi }}.tar.gz \
    dest=/opt/ creates=/opt/kibana-{{ version_kibana }}-linux-{{ controller_archi }}/package.json copy=no
    
- name: Create Kibana repository
  file: src=/opt/kibana-{{ version_kibana }}-linux-{{ controller_archi }} state=link dest=/opt/kibana
  
- name: Configure Kibana
  template: src=kibana.yml.j2 dest=/opt/kibana/config/kibana.yml \
    owner=root group=root

- name: Create Kibana Service
  copy: src=kibana dest=/etc/init.d/ mode=0755
  
- name: Start Kibana
  service: name=kibana state=started

