---

# Install
- include: install_ansible.yml
- include: install_synchro.yml
- include: install_stats.yml
- include: install_logs.yml
- include: install_src.yml

# Uninstall
- include: uninstall_ansible.yml
- include: uninstall_synchro.yml
- include: uninstall_stats.yml
- include: uninstall_logs.yml
- include: uninstall_src.yml

