---

- name: Stop openbach-backend
  service: name=openbach-backend state=stopped

- name: Remove openbach-backend service
  file: path=/etc/init.d/openbach-backend state=absent

- name: Uninstall Django
  pip: name=django state=absent

- name: Uninstall python-pip
  apt: pkg=python-pip state=absent

- name: Delete the sources
  file: path=/opt/openbach state=absent

