---

- name: Create Rstats log repository
  file: path=/var/log/openbach state=directory mode=0755

- name: Install Rstats
  copy: src=rstats/ dest=/opt/rstats/ mode=0644

- name: Configure Rstats
  template: src=rstats.cfg.j2 dest=/opt/rstats/rstats.cfg

- name: Create Rstats Service
  copy: src=rstats_service dest=/etc/init.d/rstats mode=0755

- name: Start Rstats
  service: name=rstats state=started

