---

- name: Stop Rstats
  service: name=rstats state=stopped

- name: Remove Rstats Service
  file: path=/etc/init.d/rstats state=absent

- name: Uninstall Rstats
  file: path=/opt/rstats/ state=absent

